config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get 'users/profile', to: 'users/profile#edit'
  post 'users/profile', to: 'users/profile#update'

  resources :posts do
    post 'like', on: :member
    post 'unlike', on: :member

    resources :post_comments, path: 'comments', as: :comment
  end

  post 'users/:followee/follow', to: 'users#follow', as: :users_follow
  post 'users/:followee/unfollow', to: 'users#unfollow', as: :users_unfollow

  get 'users/@:nickname', to: 'users#show_by_nickname', as: :users_show_nickname
  get 'users/:id', to: 'users#show', as: :users_show
  
  get 'feed', to: 'feed#index'

  get "up" => "rails/health#show", as: :rails_health_check
  root "posts#index"
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
  validates :text, presence: true, length: {
    minimum: 2,
    maximum: 65_000
  }
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ new create edit update destroy ]
  before_action :set_comment, only: %i[ edit update destroy ]

  # GET /post/:post_id/comments/new
  def new
    @comment = PostComment.new(post: @post, user: current_user)
  end

  # GET /post/:post_id/comments/1/edit
  def edit
  end

  # POST /post/:post_id/comments
  def create
    @comment = PostComment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    
    if @comment.save
      redirect_to post_url(@post), notice: "Comment was successfully added"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /post/:post_id/comments/1
  def update
    if @comment.update(comment_params)
      redirect_to post_url(@post), notice: "Comment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /post/:post_id/comments/1
  def destroy
    @comment.destroy!
    redirect_to post_url(@post), notice: "Post comment was successfully destroyed."
  end

  private
    def set_post
      @post = Post.find(params[:post_id])  
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = PostComment.find_by(id: params[:id], user: current_user)
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:post_comment).permit(:text)
    end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="comment">
  <p><i><%= link_to comment.user.full_name, user_url(comment.user) %> at <%=comment.created_at%></i></p>
  <pre><%= comment.text %></pre>

  <% if comment.user == current_user %>
    <%=link_to 'Edit', edit_post_comment_path(post_id: comment.post_id, id: comment.id)%>
    <%=button_to 'Delete', post_comment_path(post_id: comment.post_id, id: comment.id), method: :delete%>
  <% end %>
  <hr>
</div>

app/views/post_comments/_form.html.erb
<%= form_with(model: comment, url: (comment.id.nil? ? post_comment_index_path(comment.post_id) : post_comment_path(post_id: comment.post_id, id: comment.id) )) do |form| %>  
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this post_comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_comments/edit.html.erb
<h1>Editing post comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to post", post_path(@comment.post) %>
</div>

app/views/post_comments/new.html.erb
<h1>New post comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to post", post_path(@post) %>
</div>