config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get 'users/profile', to: 'users/profile#edit'
  post 'users/profile', to: 'users/profile#update'

  resources :posts do
    post 'like', on: :member
    post 'unlike', on: :member

    resources :post_comments, path: 'comments', as: :comment
  end

  post 'users/:followee/follow', to: 'users#follow', as: :users_follow
  post 'users/:followee/unfollow', to: 'users#unfollow', as: :users_unfollow

  get 'users/@:nickname', to: 'users#show_by_nickname', as: :users_show_nickname
  get 'users/:id', to: 'users#show', as: :users_show
  
  get 'feed', to: 'feed#index'

  get "up" => "rails/health#show", as: :rails_health_check
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  include ShrineImageUploader::Attachment(:media)

  self.per_page = 10
  default_scope { order(created_at: :desc) }

  validates :text, presence: true, length: {
    minimum: 2,
    maximum: 65_000
  }

  belongs_to :user
  has_many :likes, class_name: 'PostLike', dependent: :destroy
  has_many :comments, class_name: 'PostComment', dependent: :destroy

  def liked?(user)
    likes.where(user: user).exists?
  end

  def set_like(user)
    unless liked? user
      likes.create(user: user) 
    end
  end

  def remove_like(user)
    like = likes.where(user: user).first
    like.destroy unless like.nil? 
  end

  def generate_thumbnails
    self.media_derivatives!
    self.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[ new edit update destroy like unlike ]
  before_action :set_post, only: %i[ show like unlike ]
  before_action :set_post_edit, only: %i[ edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = PostsHelper::load_all.paginate(page: params[:page])
    @likes_map = PostsHelper::load_user_likes(current_user, @posts)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        @post.generate_thumbnails
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        @post.generate_thumbnails
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @post.set_like(current_user)
    return_url = post_url(@post)

    unless params[:url].nil?
      return_url = params[:url]
    end

    redirect_to return_url, notice: 'Great! You liked this post'
  end
  
  def unlike
    @post.remove_like(current_user)
    return_url = post_url(@post)

    unless params[:url].nil?
      return_url = params[:url]
    end

    redirect_to return_url, notice: 'Like removed'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_post_edit
    @post = Post.find_by(
      id: params[:id],
      user: current_user
    ) or not_found!
  end

  def post_params
    params.require(:post).permit(:text, :media)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_belongs_to_me?(post)
    post.user == current_user
  end

  def post_liked?(post, user, map)
    return !map[post.id].nil? unless map.nil?
    post.liked?(user)
  end

  def self.default_queryset
    Post.includes(user: [:profile])
  end

  def self.load_all
    default_queryset.all
  end

  def self.load_for_user(user)
    default_queryset.where(user: user)
  end

  def self.load_user_likes(user, posts)
    likes_map = {}
    unless user.nil?
      PostLike.where(user: user, post_id: posts.ids).each do |like|
        likes_map[like.post_id] = like  
      end
    end
      
    likes_map
  end

  def post_return_url(post)
    request.original_url + "##{dom_id post}"
  end

  def preview_image_url(post)
    return nil if post.media_data.nil?

    thumbnail = post.media(:small)
    return thumbnail.url unless thumbnail.nil?

    return post.media_url
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field half centered" style="margin-bottom: 20px;">
    <%= form.label :media, style: "display: block" %>
    <%= form.hidden_field :media, value: @post.cached_media_data, id: nil %>
    <%= form.file_field :media %>
  </div>

  <div class="field half centered">
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text, placeholder: 'Enter text' %>
  </div>

  <div class="centered">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post">
  <i>
    <%= link_to post.user.full_name, user_url(post.user) %> at <%=post.created_at%>
  </i>
  <% if post.media_data %>
    <div class="post__image-holder">
      <a href="<%=post.media_url%>" target="_blank">
        <%= image_tag preview_image_url(post), height: 300 %>
      </a>
    </div>
  <% end %>
  <pre class="post__content"><%= post.text %></pre>

  <div>
    <%= link_to "Open", post %>
    <% if post.likes_count > 0 %>
      ♥ <%=post.likes_count %>
    <% end %>

    <% unless current_user.nil? %>
      <% if post_liked?(post, current_user, @likes_map) %>
        <%= button_to 'Remove like', unlike_post_url(post, url: post_return_url(post)), method: :post %>
      <% else %>
        <%= button_to 'Like', like_post_url(post, url: post_return_url(post)), method: :post %>
      <% end %>
    <% end %>
  </div>
  <hr>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% unless current_user.nil? %>
  <%= link_to "New post", new_post_path %>
<% end %>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<% if post_belongs_to_me?(@post)%>
<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>
<% end %>

<h5>Comments:</h5>
<% @post.comments.each do |comment| %>
  <%= render 'post_comments/comment', comment: comment%>
<% end %>

<% unless current_user.nil? %>
  <h5>Add comment</h5>
  <%=render 'post_comments/form', comment: @post.comments.new%>
<% end %>