config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get 'users/profile', to: 'users/profile#edit'
  post 'users/profile', to: 'users/profile#update'

  resources :posts do
    post 'like', on: :member
    post 'unlike', on: :member

    resources :post_comments, path: 'comments', as: :comment
  end

  post 'users/:followee/follow', to: 'users#follow', as: :users_follow
  post 'users/:followee/unfollow', to: 'users#unfollow', as: :users_unfollow

  get 'users/@:nickname', to: 'users#show_by_nickname', as: :users_show_nickname
  get 'users/:id', to: 'users#show', as: :users_show
  
  get 'feed', to: 'feed#index'

  get "up" => "rails/health#show", as: :rails_health_check
  root "posts#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def not_found!
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<header class="header">
  <div class="header__title">
    <a href="/">Post-o-gramm</a>
  </div>
  <div class="header__nav">
  </div>
  <div class="header_logout">
    <% if current_user.nil? %>
      <%=link_to "Log in", new_user_session_path%>
    <% else %>
    <details>
      <summary><%=current_user.full_name%></summary>

      <li><%=link_to 'Profile', users_profile_path %></li>
      <li><%=link_to 'Security', edit_user_registration_path %></li>
      <li><%=button_to "Log out", destroy_user_session_path, :method => :delete%></li>
    </details>
    <% end %>
  </div>
</header>

<nav class="menu">
  <li><%=link_to 'All Posts', posts_path %></li>

  <% unless current_user.nil? %>
    <li><%=link_to 'My Page', user_url(current_user) %></li>
    <li><%=link_to 'My Feed', feed_url %></li>
  <% end %>
</nav>